package database

import (
	"fmt"
	"log"

	"kiskis/models"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

var DB *gorm.DB
var DBConfig Config

type Config struct {
	Host     string
	Port     int
	User     string
	Password string
	DBName   string
}

func InitDB(cfg Config) error {
	DBConfig = cfg
	dsn := fmt.Sprintf(
		"host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName,
	)

	var err error
	DB, err = gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return err
	}

	log.Println("Успешное подключение к PostgreSQL с GORM!")

	if err := DB.AutoMigrate(&models.ClaimReport{}); err != nil {
		return fmt.Errorf("ошибка миграции: %w", err)
	}

	if err := fixClaimsTable(); err != nil {
		log.Printf("Предупреждение: не удалось исправить таблицу claims: %v", err)
	}

	return nil
}

func fixClaimsTable() error {
	var count int64
	DB.Raw("SELECT 1 FROM information_schema.columns WHERE table_name = 'claims' AND column_name = 'id' AND column_default IS NOT NULL").Count(&count)
	if count == 0 {
		log.Println("Исправляем таблицу claims: добавляем автоинкремент к id")
		DB.Exec("ALTER TABLE claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
	}
	return nil
}

func CloseDB() {
	if DB != nil {
		sqlDB, _ := DB.DB()
		sqlDB.Close()
	}
}

// GetConnectionForSchema создает новое соединение для работы с определенной схемой
func GetConnectionForSchema() (*gorm.DB, error) {
	dsn := fmt.Sprintf(
		"host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		DBConfig.Host, DBConfig.Port, DBConfig.User, DBConfig.Password, DBConfig.DBName,
	)

	return gorm.Open(postgres.Open(dsn), &gorm.Config{})
}
